// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.9,
  "totalRatings": 42,
  "reviews": [
    {
      "author": "Demo-Bewertung",
      "rating": 5,
      "text": "Platzhalter für die echten Google-Bewertungen des Betriebs. Die Factory ersetzt diesen Block beim Build durch die tatsächlich gescrapten Rezensionen.",
      "time": "vor 2 Monaten"
    },
    {
      "author": "Demo-Bewertung",
      "rating": 5,
      "text": "Auch dieser Eintrag ist ein Platzhalter. Er zeigt nur, wie eine längere Rezension im Layout wirkt, damit die Kartenhöhen im Demo realistisch aussehen.",
      "time": "vor 4 Monaten"
    },
    {
      "author": "Demo-Bewertung",
      "rating": 5,
      "text": "Dritter Platzhalter für die Layout-Vorschau.",
      "time": "vor 7 Monaten"
    }
  ]
};
